- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature-tracking.md
This commit adds issue templates for BUG reports and internal feature tracking. This allows us to have a consistent look and feel for all issues.
> Update issue templates

- Dockerfile
- config.toml
Update Dockerfile to use debian in application container,
to temporarily fix the bug `exec ./aruna_server: no such file or directory` in alpine.
> Update Dockerfile to debian only and config.toml

- Cargo.lock
- Cargo.toml
- config/config.toml
- src/config.rs
- src/database/crud/collection.rs
- src/database/crud/info.rs
- src/database/crud/mod.rs
- src/database/crud/object.rs
- src/database/crud/objectgroups.rs
- src/database/crud/user.rs
- src/database/crud/utils.rs
- src/database/models/views.rs
- src/database/schema.rs
- src/error.rs
- src/server/grpc_server.rs
- src/server/services/collection.rs
- src/server/services/info.rs
- src/server/services/internal_authorize.rs
- src/server/services/internal_notifications.rs
- src/server/services/mod.rs
- src/server/services/object.rs
- src/server/services/objectgroup.rs
- src/server/services/service_account.rs
- tests/b1_authz_test.rs
- tests/b2_authz_user_grpc_test.rs
- tests/c_project_tests.rs
- tests/common/functions.rs
- tests/d_collection_tests.rs
- tests/e_object_tests.rs
- tests/i_info_grpc.rs
PR that accumulates various changes from 0.5.0 and previous beta development to the dev branch.
The changes include:
- Updated API to 0.5.0
- AddLabelsToObjectGroup request (inline with similar Object request)
- Limits update functionality without force to only the most recent object to prevent concurrency issues
- First iteration of an info service that provides status and version information for registered components
- Various added tests for info service
- Stubs for the notification service (currently unavailable)
- Stubs for the service account service (currently unavailable)
A more sophisticated changelog is provided via the commitlog.
This is the first stable release for 0.5.0, please report any issues that occur with this release.
> merge: Add changes from 0.5.0 dev to dev branch

- src/database/crud/collection.rs
Without this filter, a collection update overwrites all registered collections with the provided collection meta information.
> Hotfix: Add missing filter to collection update

- migrations/2023-02-03-103413_parallel_collection_object/down.sql
- migrations/2023-02-03-103413_parallel_collection_object/up.sql
- src/database/crud/collection.rs
- src/database/crud/object.rs
- src/server/services/object.rs
- tests/common/functions.rs
- tests/e1_object_tests.rs
- tests/e2_objects_grpc_test.rs
- tests/sources/up.sql
This extends the test coverage over the gRPC Service functions including some edge cases that may occur in day to day usage of the AOS. This PR additionally deals with inconsistencies that may occur due to the previous implementation of the functionality to delete objects. Details about the bugs that have been fixed can be found under _Changes_  using the linked issues.
* Object CRUD test for object deletion from versioned collections
* gRPC ObjectService - Individual object deletion with/without revisions
* gRPC ObjectService - Multiple object deletion with/without revisions
* Objects can no longer be deleted from versioned collections (Fixes #59)
* Outdated revisions can be deleted under specific circumstances (Fixes #60)
* Dangling objects without a writable reference in at least one …
> Add additional tests for gRPC service functions

- Cargo.lock
- Cargo.toml
- migrations/2023-02-03-103413_parallel_collection_object/down.sql
- migrations/2023-02-03-103413_parallel_collection_object/up.sql
- migrations/2023-02-13-113213_add_paths/down.sql
- migrations/2023-02-13-113213_add_paths/up.sql
- src/database/crud/collection.rs
- src/database/crud/object.rs
- src/database/crud/objectgroups.rs
- src/database/crud/project.rs
- src/database/crud/user.rs
- src/database/crud/utils.rs
- src/database/models/enums.rs
- src/database/models/object.rs
- src/lib.rs
- src/server/services/internal_proxy_notifier.rs
- src/server/services/mod.rs
- src/server/services/object.rs
- tests/b1_authz_test.rs
- tests/b2_authz_user_grpc_test.rs
- tests/c1_project_tests.rs
- tests/c2_project_grpc_tests.rs
- tests/common/functions.rs
- tests/d1_collection_tests.rs
- tests/d2_collection_grpc_tests.rs
- tests/e1_object_tests.rs
- tests/e2_objects_grpc_test.rs
- tests/e3_object_path_grpc_tests.rs
- tests/f_object_groups.rs
- tests/sources/up.sql
This adds all the changes since ArunaAPI version 1.0.0-rc.1.
* Added dummy implementation of paths logic for objects as prerequisite for the upcoming S3 compatibility
* Convert origin_id to a mandatory field for an object
* Implementation of paths logic for objects as prerequisite for the upcoming S3 compatibility
* Implemented tests for all the object path functionality 
* Hash can be added now to an object on creation with the `InitializeNewObjectRequest`
* Removed the type from the origin part of a returned object as it poses no added value for the user
* Limit project/collection names to [RFC3986 unreserved characters](https://www.rfc-editor.org/rfc/rfc3986#section-2.3) for path compliance
* Rollback useless migration which allowed objects to have two references (one static and one …
> Update Server to ArunaAPI 1.0.0-rc.5

- src/database/crud/object.rs
- src/database/crud/user.rs
This fixes #67 as it introduces a filter for already deleted revisions on getting the latest object revision.
> Ignore deleted revisions in get_latest_obj(...)

- .gitignore
- src/database/crud/object.rs
- tests/e2_objects_grpc_test.rs
This PR changes the object update logic in a way that concurrent updates of individual objects are no longer possible.
This has the background that the planned S3 interface of the AOS would not be compatible with multiple staging objects at the same time. The assignment of an upload via an object path would simply be impossible in many cases with concurrent updates. In addition, this simplifies the maintenance of the consistency of objects by a considerable degree.
> Refactor object update logic to prohibit concurrent updates

- Cargo.lock
- migrations/2022-12-02-110911_unique_user_permissions/down.sql
- migrations/2023-02-13-113213_add_paths/down.sql
- migrations/2023-05-15-081831_indices/down.sql
- migrations/2023-05-15-081831_indices/up.sql
- src/database/crud/authz.rs
- src/database/crud/object.rs
- src/server/services/object.rs
- src/server/services/user.rs
- tests/sources/up.sql
This is a first set of fixes for #75 
Very large database transactions lead to a high likelihood of table and index contention. To temporarily make this problem less prominent this PR includes the following changes:
- Added more indices for heavy contended tables (collection_object, paths etc.)
- Added retry with backoff for inserts and auth
- Added some querys with `FOR UPDATE` selects to lock rows before they are updated.
This heavily reduces the number of contention events but does not eliminate them completely. Future fixes should address this by either reducing overall transaction size and/or denormalization of tables to reduce needed locks / tracked relations.
> feat: Contention fixes

- src/database/crud/collection.rs
- tests/common/functions.rs
- tests/d2_collection_grpc_tests.rs
Small PR which fixes #88 .
* `required_label` entries associated with the collection are also deleted before the collection itself
> Fix collection deletion including required labels

- Cargo.lock
- Cargo.toml
- src/database/crud/authz.rs
- src/database/crud/mod.rs
- src/database/crud/object.rs
- src/database/crud/project.rs
- src/database/crud/service_accounts.rs
- src/database/crud/user.rs
- src/database/models/auth.rs
- src/error.rs
- src/server/services/authz.rs
- src/server/services/collection.rs
- src/server/services/internal_authorize.rs
- src/server/services/internal_proxy_notifier.rs
- src/server/services/object.rs
- src/server/services/project.rs
- src/server/services/service_account.rs
- src/server/services/user.rs
- tests/b1_authz_test.rs
This PR builds on top of PR #90 . It adds the long awaited `ServiceAccount` feature.
Service accounts are similar to regular users but have some restrictions:
- Service accounts are always bound to exactly one project and cannot be added to other projects
- SAs are managed via a separate API that has a similar interface as the user equivalent but can be called as `Project::ADMIN`
- Service accounts can do the same things as regular users with the exception user management requests, these are (for now) "real" user only.
This PR implements all necessary API and DB requests that make it possible to create, update and manage service accounts by Project Admins. The API should be treated as BETA for now.
The PR also adds some optimizations in the ApiToken <-> gRPC Token handling by introducing …
> feat: Feat/service accounts

- tests/common/functions.rs
- tests/j_internal_notifications_test.rs
This PR adds a basic set of tests for the CRUD database functions which were implemented with the InternalNotificationService. To ensure the stability and consistency requirements of the AOS, tests are of course essential. Therefore, these will be provided as soon as possible if they were not delivered directly with a service implementation.
> Add tests for stream group crud functions

- src/auth/permission_handler.rs
- src/auth/structs.rs
- src/auth/token_handler.rs
- src/caching/cache.rs
- src/caching/structs.rs
- src/database/dsls/internal_relation_dsl.rs
- src/database/dsls/mod.rs
- src/database/dsls/object_dsl.rs
- src/database/dsls/pub_key_dsl.rs
- src/database/dsls/user_dsl.rs
- src/database/enums.rs
- src/database/schema.sql
- src/grpc/collections.rs
- src/grpc/datasets.rs
- src/grpc/notification.rs
- src/grpc/object.rs
- src/grpc/projects.rs
- src/middlelayer/create_db_handler.rs
- tests/objects.rs
- tests/users.rs
A basic / crude implementation of caching / authorization including path traversal.
- Check contexts of requests
- Check user permissions based on cached values
- Decode Tokens based on pubkeys
> [feat] Feat/caching auth

- src/auth/permission_handler.rs
- src/auth/token_handler.rs
- src/caching/mod.rs
- src/caching/notifications_handler.rs
- src/database/dsls/pub_key_dsl.rs
- src/grpc/notification.rs
- src/grpc/users.rs
- src/main.rs
- src/notification/natsio_handler.rs
- src/notification/utils.rs
- src/utils/conversions.rs
- tests/common/init_db.rs
- tests/database/pub_keys.rs
This extends the ArunaServer with a basic implementation of NotificationHandling, which will be used to keep the cache up-to-date in the future.
In addition, the ArunaServer receives a basic start-up procedure, which will of course be considerably expanded in the future to ensure complete consistency of the instance after start-up. This will include, for example, a complete synchronisation of the cache against the database for the first time.
* Notification handling for cache updates
* Basic startup procedure to start the individual services
* Only EndpointService available until default Dataproxy is configured
* Cache sync on startup
* ...
> Basic NotificationsHandler and startup

- src/caching/cache.rs
- src/caching/structs.rs
- src/database/dsls/object_dsl.rs
- src/database/dsls/user_dsl.rs
- src/grpc/authorization.rs
- src/main.rs
- src/middlelayer/user_db_handler.rs
- tests/database/users.rs
This implements the missing gRPC functions of the `AuthorizationService`.
- Permissions on resources can now get fetched, removed and updated
- After many tries Clippy convinced me to implement the `Default` trait for `Cache`
> Implement AuthorizationService

- src/grpc/notification.rs
- src/middlelayer/clone_db_handler.rs
- src/middlelayer/create_db_handler.rs
- src/middlelayer/delete_db_handler.rs
- src/middlelayer/relations_db_handler.rs
- src/middlelayer/snapshot_db_handler.rs
- src/middlelayer/update_db_handler.rs
- src/notification/handler.rs
- src/notification/natsio_handler.rs
- src/notification/utils.rs
- tests/notifications.rs
This adds message deduplication to the integrated notification concept.
Since the hierarchy concept allows the same notification to be sent to a consumer multiple times, it is beneficial to perform internal deduplication. 
If a notification with the same content is sent for several hierarchies of a resource, these notifications are provided with the same ULID in their header (`"block-id": ULID`). This ULID is used to re-identify the message blocks that belong together when a consumer retrieves several of them.
This ensures that each notification within a particular action in the AOS is only delivered once to the user.
> Add message deduplication

- src/auth/issuer_handler.rs
- src/auth/token_handler.rs
- src/caching/cache.rs
- src/caching/notifications_handler.rs
- src/database/dsls/object_dsl.rs
- src/database/dsls/user_dsl.rs
- src/middlelayer/endpoints_db_handler.rs
- src/middlelayer/user_db_handler.rs
- src/middlelayer/workspace_request_types.rs
- tests/database/objects.rs
- tests/database/users.rs
This PR extends the removal of endpoints. 
The following additional steps are taken when an endpoint is completely removed from the AOS system:
* Removal of the endpoint id from the `trusted_endpoints` attribute of all users
* Removal of the endpoint from all objects (equivalent to the removal of the object replica at this endpoint)
Warning: If an object only has a replica of its data at this one endpoint, this data is lost when the endpoint is removed!
> Extended endpoint removal

- src/caching/cache.rs
- src/caching/structs.rs
- src/middlelayer/delete_db_handler.rs
- src/middlelayer/hooks_db_handler.rs
- tests/database/stats.rs
- tests/middlelayer/delete.rs
Changes to the resource deletion concept had the unintended effect of removing deleted resources from permission handling. As a result, deleted resources could no longer be requested by users at all.
This PR fixes two bugs directly involved in the deletion handling process and resolves #142.
> Fix deleted resources permission handling

- components/server/src/grpc/relations.rs
- components/server/src/hooks/hook_handler.rs
- components/server/src/middlelayer/create_db_handler.rs
- components/server/src/middlelayer/create_request_types.rs
- components/server/src/middlelayer/relations_db_handler.rs
- components/server/src/middlelayer/relations_request_types.rs
- components/server/src/utils/conversions/relations.rs
- components/server/tests/middlelayer/create.rs
- components/server/tests/middlelayer/relations.rs
Fix for `CreateRequests`. 
Due to the rules update, all changes to resources are captured by a database transaction, to check for possible rule violations in the changed state. Added relations were checked in the cache, where the changed state was not present. This check is now done via the database and a `transaction_client`.
> fix: Fixed added relations for create requests

- components/server/src/grpc/search.rs
`get_resource()` now returns the correct permission a user has for the resource or `PermissionLevel::None` if the user does not have permissions on the resource or is not authenticated at all.
> Fix get_resource 

- components/server/src/hooks/hook_handler.rs
- components/server/src/middlelayer/hooks_request_types.rs
- components/server/src/middlelayer/presigned_url_handler.rs
- components/server/src/middlelayer/workspace_db_handler.rs
This small upgrade fixes an regression in the pre-signed URL handler.
Previous iterations had a GetOrCreate method for fetching Credentials from a proxy. This was changed during the 2.0 update resulting in an unauthorized error when making a Get call before a create call.
This update reverts this behavior on the server site.
It also simplifies and removes some unnecessary redundancy in the hook handling logic.
> fix: Update presign handler

- components/data_proxy/src/caching/cache.rs
- components/data_proxy/src/structs.rs
Comparing permissions was switched, resulting in no permission updates
> fix: Fixed upsert user comparison

- components/server/src/grpc/object.rs
This adds an additional permission check for cloned_objects and updates needed parent permissions from `WRITE` to `APPEND`
> fix: clone_object permission check

- components/data_proxy/config.toml
- components/data_proxy/src/config.rs
- components/data_proxy/src/data_backends/s3_backend.rs
This adds a config value for path-style buckets, to address legacy (and deprecated) s3 backend configurations
> feat: Config option to force deprecated path style buckets in s3 backend

- Cargo.lock
- components/data_proxy/.env
- components/data_proxy/Cargo.toml
- components/data_proxy/config.toml
- components/data_proxy/src/config.rs
- components/data_proxy/src/main.rs
- components/data_proxy/src/s3_frontend/s3server.rs
- components/data_proxy/src/s3_frontend/s3service.rs
- components/server/tests/database/relations.rs
Adds a config parameter that can be used to set CORS exceptions for certain origins via regex.
Requests with an `Origin` header whose value matches the regex always receive the following CORS response headers in the response:
- `Access-Control-Allow-Origin: *`
- `Access-Control-Allow-Methods: *`
- `Access-Control-Allow-Headers: *`
This allows the operators of a DataProxy to release its resources for interactions with certain applications. If the parameter is not set, only the set bucket CORS rules are applied as before.
> CORS exception regex

- components/data_proxy/src/s3_frontend/s3service.rs
This addresses a bug in the `put_object` process where the system incorrectly evaluated whether an updated object was initialized which leads to an error when the system tries to create a duplicate of the already existing object after the upload.
This fix ensures that the system accurately tracks whether a new object has been initialized on update through the data proxy's S3 interface and does not erroneously attempt to create a duplicate.
> fix: Incorrect evaluation if object was initialized

- components/server/src/grpc/users.rs
- components/server/src/main.rs
- components/server/src/middlelayer/user_db_handler.rs
- components/server/tests/common/init.rs
This re-implements mail notifications for users upon registration and activation.
Mail notification is sent to the email address provided by the user:
* After a successful `RegisterUserRequest` 
* After a success `ActivateUserRequest`
But only in case the config parameter `ARUNA_DEV_ENV` is set to `true` and valid values for the SMTP server are also provided.
If it turns out that in the future even more mail notifications are to be sent directly via the Aruna server, you could think about a kind of template or configuration to overwrite the hard-coded mail content.
> Mail notifications

- components/data_proxy/Dockerfile
- components/server/Dockerfile
This pull request addresses the issue of broken containers caused by outdated Dockerfile images. The current images were leading to runtime errors. This update refreshes the images to ensure the containers are built and run reliably.
> Update dockerfile images

- components/server/src/database/dsls/object_dsl.rs
- components/server/src/grpc/search.rs
* Resource fetch without token now correctly filters key-values tagged as private or internal
* Check if project exists now does not incorrectly include its direct children anymore
> Fix filter for resource key-values and project exists query

- Cargo.lock
- Cargo.toml
- components/server/.env
- components/server/src/database/dsls/info_dsl.rs
- components/server/src/database/dsls/mod.rs
- components/server/src/database/schema.sql
- components/server/src/grpc/info.rs
- components/server/src/grpc/users.rs
- components/server/src/middlelayer/announcements_db_handler.rs
- components/server/src/middlelayer/mod.rs
- components/server/src/utils/conversions/announcements.rs
- components/server/src/utils/conversions/mod.rs
- components/server/tests/common/init.rs
- components/server/tests/common/test_utils.rs
- components/server/tests/database/announcements.rs
- components/server/tests/database/mod.rs
- components/server/tests/grpc/info.rs
- components/server/tests/grpc/mod.rs
- components/server/tests/middlelayer/announcements.rs
- components/server/tests/middlelayer/mod.rs
This pull request introduces the implementation of the  announcements API part of the StorageStatusServer. The implemented API endpoints allow Aruna administrators to create and manage public announcements, providing a natively integrated capability for handling announcement data. Retrieval is publicly available without the need for authentication which provides an easily accessible way for everyone to display the announcements in other services.
In addition to the API implementation, extensive unit testing is included to ensure the reliability and correctness of the new functionality.
* Update `aruna_rust_api` dependency to version 2.0.0-beta.15.1
* Extends the database schema with the table `announcements`
* Implements the `StorageStatusServer` API endpoints `set_announcements`, …
> StorageStatusServer announcements API implementation

- Cargo.lock
- Cargo.toml
- components/server/src/database/dsls/info_dsl.rs
- components/server/src/utils/conversions/announcements.rs
- components/server/src/utils/grpc_utils.rs
- components/server/tests/database/announcements.rs
- components/server/tests/grpc/info.rs
- components/server/tests/middlelayer/announcements.rs
This refactors parts of the public announcement implementation, especially regarding the creation and fetching of announcements. 
* Fetching now always returns the announcements sorted with newest first
* Creation timestamp and the id are now tightly coupled to avoid breaking pagination
* Announcements can be created with a specific timestamp which will be used for the id generation if the id is empty
> Refactor public announcements

- Cargo.lock
- Cargo.toml
- components/server/src/database/dsls/object_dsl.rs
- compose_deploy.yaml
This fixes a missing type filter in the SQL queries responsible for fetching a valid hierarchy of a resource.
> Add missing relation type filter

- components/server/src/middlelayer/presigned_url_handler.rs
This addresses an issue with the handling of multipart part numbers when generating presigned URLs. Previously, part numbers were incorrectly evaluated, leading to errors with valid part numbers. This fix ensures that part numbers are now evaluated and managed accurately.
> Correct multipart part number handling

- components/data_proxy/src/caching/cache.rs
- components/data_proxy/src/data_backends/s3_backend.rs
- components/data_proxy/src/replication/replication_handler.rs
- components/data_proxy/src/s3_frontend/data_handler.rs
- components/data_proxy/src/s3_frontend/s3service.rs
- components/data_proxy/src/s3_frontend/utils/list_objects.rs
This PR implements support for the legacy S3 `ListObjects` API operation. Note that this function has been superseded by `ListObjectsV2` and is included solely for backwards compatibility with existing systems that may still rely on the original API.
**Important:** This implementation will not receive feature updates or enhancements going forward. New integrations should use `ListObjectsV2` instead, which provides better performance and additional functionality.
> Backwards compatibility for ListObjects

- components/data_proxy/src/caching/cache.rs
- components/data_proxy/src/caching/grpc_query_handler.rs
- components/data_proxy/src/s3_frontend/s3server.rs
- components/data_proxy/src/s3_frontend/s3service.rs
- components/server/src/database/dsls/object_dsl.rs
- components/server/src/middlelayer/update_db_handler.rs
Fixed:
- When OPTIONS requests are made, bucket-specific CORS configurations are returned
- Only CORS headers for ORIGIN are returned
- Authors are now also updated in database
- CORS headers are either set or deleted, not both
> fix: Fixed CORS headers in dataproxy, authors in server
